modLoader="javafml"
loaderVersion="[40,)"
license="Not specified"

[[mods]]
modId="slightly_vanilla_additions"
version="1.0.0"
displayName="Slightly Vanilla Additions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="puikw, MCreator"

[[dependencies.slightly_vanilla_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




